extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
      argsIgnorePattern: ^_
  semi: 2
  quotes: ['error', 'single']
  quote-props: ['error', 'consistent-as-needed']
  comma-dangle: ['error', 'always-multiline']
  indent: [warn, 4, {SwitchCase: 1}]
  eqeqeq: error
  prefer-arrow-callback: error
  no-constant-condition: [error, { checkLoops: false }]

  # spacing
  no-trailing-spaces: error
  func-call-spacing: error
  object-curly-spacing: [error, always]
  array-bracket-spacing: error
  computed-property-spacing: error
  space-before-blocks: error
  arrow-spacing: error
  keyword-spacing: error
  key-spacing: error
  space-infix-ops: error
